# This applies to the airwave-tiller namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: airwave-tiller
---  
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: airwave-tiller
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: airwave-tiller
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: airwave-tiller
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io